export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      colors: {
        background: '#111316',
        surface: '#111316',
        'surface-bright': '#37393d',
        'surface-dim': '#111316',
        'surface-container': '#1e2023',
        'surface-container-low': '#1a1c1f',
        'surface-container-lowest': '#0c0e11',
        'surface-container-high': '#282a2d',
        'surface-container-highest': '#333538',
        primary: '#59de9b',
        'primary-container': '#00a86b',
        'on-primary': '#003921',
        'on-primary-container': '#00331d',
        'primary-fixed': '#78fbb6',
        'primary-fixed-dim': '#59de9b',
        secondary: '#e9c349',
        'secondary-container': '#af8d11',
        'on-secondary': '#3c2f00',
        'secondary-fixed': '#ffe088',
        'secondary-fixed-dim': '#e9c349',
        tertiary: '#ffb4ac',
        'tertiary-container': '#ff5950',
        'on-tertiary': '#690006',
        'tertiary-fixed': '#ffdad6',
        'on-tertiary-fixed': '#410002',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-background': '#e2e2e6',
        'on-surface': '#e2e2e6',
        'on-surface-variant': '#bccabe',
        outline: '#869489',
        'outline-variant': '#3d4a41',
        'inverse-on-surface': '#2f3034',
        'inverse-surface': '#e2e2e6',
        'inverse-primary': '#006d43',
      },
      keyframes: {
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%':      { transform: 'translateX(-8px)' },
          '75%':      { transform: 'translateX(8px)' },
        },
        float: {
          '0%':   { opacity: 1, transform: 'translateY(0)' },
          '100%': { opacity: 0, transform: 'translateY(-50px)' },
        },
        slideDown: {
          '0%':   { opacity: 0, transform: 'translateY(-20px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
      },
      animation: {
        shake: 'shake 0.4s ease',
        float: 'float 1s ease forwards',
        slideDown: 'slideDown 0.3s ease',
      },
    },
  },
  plugins: [],
}